
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2
    networks:
      - backend

  service_1:
    build: ./service_1
    expose:
      - "8001"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 30s
      timeout: 5s
      retries: 3

  service_2:
    build: ./service_2
    expose:
      - "8002"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8002/"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  backend:
    driver: bridge
